language: java
jdk:
  - openjdk11

branches:
  only:
    - main # git default 브런치를 등록한다. (ex. master)

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - ynhyojng@gmail.com