spring:

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 658312263287-danrtjun8da6im0r5rudcsg6e6au5kok.apps.googleusercontent.com
              client-secret: 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
              scope: profile, email

            kakao:
              client-id: 805bbf422b921a63ed8df325ed13428b
              client-secret: KMbqaAreZ6U2sZkOr5Q0qOPGrUyRQyHG
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
              scope: profile_nickname, profile_image, account_email
              client-name: kakao
              client-authentication-method: POST

          provider:
            kakao:
              authorization_uri: https://kauth.kakao.com/oauth/authorize
              token_uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user_name_attribute: id
  jwt:
    secretKey: "q09ew8edjikadgffl;dfghkjnawehog"
    signatureAlgorithm: HS256
    tokenExpired: 604800 #(sec) 7 days

